import { useState } from 'react';
import { AlertCircle, Calculator, CheckCircle2, ChevronRight, Database, FileSpreadsheet, HelpCircle, Layers, Lightbulb, X } from 'lucide-react';

const METRICS = [
  {
    id: 'warRoom', name: 'War Room Report', descriptor: 'Logistics Cost', unit: '%', badge: 'Lower is better', color: '#3B82F6',
    formula: 'Logistics Cost (%) = Total Logistics Cost ÷ Gross Production Value',
    concept: 'Percentage of total logistics handling costs relative to the gross production value of TVs.',
    source: 'War Room Report, “Logistic” sheet, row 67. Received by weekly operational email.',
    businessRule: 'Measures logistics efficiency relative to factory output. As production grows, nominal freight may increase, while the percentage should decrease or remain stable through scale gains.',
    statusRule: 'Green: ≥ 100% achievement · Yellow: 90%–99.99% · Red: < 90%',
    example: 'Jan/26: 5.4% actual against a 6.5% ceiling results in approximately 120% target achievement (green).',
  },
  {
    id: 'airFreight', name: 'Air Freight', descriptor: 'Emergency freight cost', unit: '%', badge: 'Crisis monitoring', color: '#38BDF8',
    formula: 'Monthly = Freight Amount ÷ Material Cost\nAnnual ACC = Σ Freight Amount ÷ Σ Material Cost',
    concept: 'Share of unplanned emergency air freight costs in relation to total TV material cost.',
    source: 'Freight Air monthly report, “Annual Result” sheet, rows 8 and 9. Received by monthly email; manual entry remains available.',
    businessRule: 'Tracks supply shortages and component delays that require urgent transportation. A target is available from 2026; 2024 and 2025 are historical periods without a target.',
    validation: 'The calculated annual ACC is checked against the accumulated columns available in the source report. Divergences must be reviewed.',
    statusRule: 'Green: ≥ 100% achievement · Yellow: 90%–99.99% · Red: < 90%',
    example: 'Jul/26: 0.358% actual against a 0.22% target results in 61.36% achievement (red).',
  },
  {
    id: 'resinConsolidation', name: 'Resin Consolidation', descriptor: 'Resin optimization saving', unit: 'KUSD', badge: 'Saving', color: '#2563EB',
    formula: 'Net Saving = Gross Saving (20 ft container) − Global Costs − Brazilian Taxes (34.39%)',
    concept: 'Net financial saving generated by consolidating plastic resin shipments in 40 ft containers instead of 20 ft containers.',
    source: 'Incidental Cost report, “Resin Consolidation” sheet. Received by monthly operational email.',
    businessRule: 'Positive saving represents a direct productivity gain. Quarterly, semiannual and annual results are accumulated by sum.',
    statusRule: 'No target-achievement status is displayed for this indicator.',
    example: 'Jun/26: USD 3.34 K in net saving generated by the Manaus operation.',
  },
  {
    id: 'taskCost', name: 'Task Cost Reduction', descriptor: 'Operational cost reduction', unit: 'KBRL', badge: 'Cost saving', color: '#1D4ED8',
    formula: 'Achieved Reduction = Budgeted Costs − Actual Costs',
    concept: 'Nominal reduction in logistics task and process costs delivered by the team.',
    source: 'Task Cost Reduction spreadsheet and monthly controlling report.',
    businessRule: 'Measures continuous operational cost-reduction projects. Quarterly, semiannual and annual results are accumulated by sum.',
    statusRule: 'Green: ≥ 100% achievement · Yellow: 90%–99.99% · Red: < 90%',
    example: 'Jun/26: BRL 688 K in accumulated reduction against a BRL 641 K target.',
  },
  {
    id: 'demurrage', name: 'Demurrage Cost', descriptor: 'Container overstay', unit: 'CTNR', badge: 'Zero target', color: '#0EA5E9',
    formula: 'Demurrage = Number of containers retained beyond free time',
    concept: 'Total containers charged additional daily fees due to delays in unloading and returning empty equipment.',
    source: 'Demurrage Cost report and shipping-line empty-container return control.',
    businessRule: 'The target is exactly zero containers. Any value above zero represents financial loss and an operational delay.',
    statusRule: 'Green: 0 containers · Red: more than 0 containers',
    example: 'A period with 5 containers beyond free time is classified as red.',
  },
  {
    id: 'incidentalCost', name: 'Incidental Cost', descriptor: 'Logistics cost vs production', unit: 'Ratio', badge: 'Direct ratio', color: '#7C3AED',
    formula: 'Incidental Cost Ratio = Incidental Cost (MUSD) ÷ Production Amount (MUSD)',
    concept: 'Relationship between incidental logistics expenditure and the corresponding production amount.',
    source: 'Incidental Cost_Total report, “Incidental Cost (MUSD)” sheet: row 82 (cost), row 95 (production) and row 96 (reported ratio). Received by monthly email.',
    businessRule: 'Monthly values are calculated directly. Quarterly, semiannual and annual results use the sum of cost divided by the sum of production.',
    validation: 'The calculated monthly ratio is checked against the percentage reported on row 96 for the same year and month.',
    statusRule: 'Not applicable. This indicator has no fixed target and no target-achievement status.',
    example: 'Jun/26: USD 2.64 M ÷ USD 49.27 M = 5.36%.',
  },
];

function DetailBlock({ icon: Icon, label, children, accent = false }) {
  return (
    <section className={`metric-guide__block${accent ? ' metric-guide__block--accent' : ''}`}>
      <div className="metric-guide__block-title"><Icon size={15} />{label}</div>
      <div className="metric-guide__block-content">{children}</div>
    </section>
  );
}

function StatusRule({ metric }) {
  if (metric.id === 'resinConsolidation' || metric.id === 'incidentalCost') {
    return <span className="metric-status-rule metric-status-rule--neutral"><span className="metric-status-dot metric-status-dot--neutral" />{metric.statusRule}</span>;
  }

  if (metric.id === 'demurrage') {
    return (
      <div className="metric-status-list">
        <span className="metric-status-rule"><span className="metric-status-dot metric-status-dot--green" /><strong>Green</strong> 0 containers</span>
        <span className="metric-status-rule"><span className="metric-status-dot metric-status-dot--red" /><strong>Red</strong> More than 0 containers</span>
      </div>
    );
  }

  return (
    <div className="metric-status-list">
      <span className="metric-status-rule"><span className="metric-status-dot metric-status-dot--green" /><strong>Green</strong> ≥ 100% achievement</span>
      <span className="metric-status-rule"><span className="metric-status-dot metric-status-dot--yellow" /><strong>Yellow</strong> 90%–99.99%</span>
      <span className="metric-status-rule"><span className="metric-status-dot metric-status-dot--red" /><strong>Red</strong> &lt; 90%</span>
    </div>
  );
}

export default function MetricsModal({ isOpen, onClose }) {
  const [activeId, setActiveId] = useState(METRICS[0].id);
  if (!isOpen) return null;
  const metric = METRICS.find((item) => item.id === activeId) || METRICS[0];

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content metrics-modal" onClick={(event) => event.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-title">
            <Database size={20} className="modal-title-icon" />
            <div><h3>Metric Dictionary & Data Origin</h3><p>Definitions, formulas, official sources and calculation rules</p></div>
          </div>
          <button className="btn-close" onClick={onClose} aria-label="Close metric guide"><X size={18} /></button>
        </div>

        <div className="metrics-modal__body">
          <div className="metrics-intro-card">
            <HelpCircle size={18} />
            <div><strong>How to use this guide</strong><p>Select a metric to understand what it measures, where its data comes from and how its result is calculated.</p></div>
          </div>

          <div className="metrics-guide">
            <nav className="metrics-guide__nav" aria-label="Metric list">
              <div className="metrics-guide__nav-label">Available metrics</div>
              {METRICS.map((item, index) => (
                <button type="button" key={item.id} className={`metrics-guide__nav-item${item.id === metric.id ? ' active' : ''}`} onClick={() => setActiveId(item.id)} style={{ '--metric-color': item.color }}>
                  <span className="metrics-guide__nav-number">{String(index + 1).padStart(2, '0')}</span>
                  <span><strong>{item.name}</strong><small>{item.unit} · {item.descriptor}</small></span>
                  <ChevronRight size={15} />
                </button>
              ))}
            </nav>

            <article className="metric-guide__detail" style={{ '--metric-color': metric.color }}>
              <header className="metric-guide__header">
                <div><span className="metric-guide__eyebrow">Metric definition</span><h4>{metric.name}</h4><p>{metric.descriptor}</p></div>
                <div className="metric-guide__tags"><span>{metric.unit}</span><span>{metric.badge}</span></div>
              </header>
              <DetailBlock icon={Calculator} label="Formula" accent><code>{metric.formula}</code></DetailBlock>
              <div className="metric-guide__columns">
                <DetailBlock icon={Layers} label="Concept">{metric.concept}</DetailBlock>
                <DetailBlock icon={FileSpreadsheet} label="Data origin">{metric.source}</DetailBlock>
              </div>
              <DetailBlock icon={CheckCircle2} label="Business rule">{metric.businessRule}</DetailBlock>
              {metric.validation && <DetailBlock icon={AlertCircle} label="Data validation">{metric.validation}</DetailBlock>}
              <DetailBlock icon={Database} label="Status rule"><StatusRule metric={metric} /></DetailBlock>
              <DetailBlock icon={Lightbulb} label="Practical example" accent>{metric.example}</DetailBlock>
            </article>
          </div>
        </div>

        <div className="modal-footer"><button className="btn btn--primary" onClick={onClose}>Close guide</button></div>
      </div>
    </div>
  );
}
