"""estrutura inicial completa

Revision ID: 0e4b193a8f14
Revises: 
Create Date: 2026-08-24 03:21:37.932457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4b193a8f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_air_freight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_air_freight_month_year')
    )
    op.create_table('kpi_demurrage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_demurrage_month_year')
    )
    op.create_table('kpi_incidental_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_incidental_cost_month_year')
    )
    op.create_table('kpi_logistic_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_logistic_cost_month_year')
    )
    op.create_table('kpi_logistics_vs_prod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('logistics_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('production_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_logistics_vs_prod_month_year')
    )
    op.create_table('kpi_total_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('result', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('achievement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'year', name='uq_total_cost_month_year')
    )
    op.create_table('processed_emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_emails_message_id'), 'processed_emails', ['message_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_processed_emails_message_id'), table_name='processed_emails')
    op.drop_table('processed_emails')
    op.drop_table('kpi_total_cost')
    op.drop_table('kpi_logistics_vs_prod')
    op.drop_table('kpi_logistic_cost')
    op.drop_table('kpi_incidental_cost')
    op.drop_table('kpi_demurrage')
    op.drop_table('kpi_air_freight')
    # ### end Alembic commands ###
